CREATE TABLE "work" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "config" INTEGER NOT NULL);
CREATE TABLE "corse" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT, "time" INTEGER NOT NULL, "interval" INTEGER NOT NULL,"rest" INTEGER NOT NULL);
CREATE TABLE "up"("_id" INTEGER PRIMARY KEY AUTOINCREMENT)